name: NEUS642-test
channels:
  - defaults
dependencies:
  - cython
  - git
  - ipykernel
  - matplotlib>=3.0.0
  - numpy>=1.15.2
  - pandas>=0.23.4
  - pillow>=5.3.0
  - python>=3.6.0
  - scipy>=1.1.0
  - seaborn>=0.9.0
  - pip:
    - czifile==0.1.5
    - pyabf==2.0.21
    - tifffile==0.15.1
